#!/bin/bash
echo -e "\
cat /proc/cmdline - Show current boot parameter\n\
nano /etc/default/grub && update-grub - Under Ubuntu using grub, change boot parameter/behaviour
\n\
-------------------------------------------------------------------------------\n\

"